param(
    [string]$HaConfigDrive = "Z:",
    [switch]$SkipBuild,
    [switch]$NoSourceMap
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Step([string]$Message) {
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Require-Command([string]$Name) {
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Required command '$Name' was not found in PATH."
    }
}

$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$DistDir     = Join-Path $ProjectRoot "dist"
$Bundle      = Join-Path $DistDir "yardian-card.js"
$SourceMap   = Join-Path $DistDir "yardian-card.js.map"
$BuildInfo   = Join-Path $DistDir "build-info.json"

# Z: is the Home Assistant /config directory via Samba.
$RemoteDir   = Join-Path $HaConfigDrive "www\yardian-card"
$RemoteJs    = Join-Path $RemoteDir "yardian-card.js"
$RemoteMap   = Join-Path $RemoteDir "yardian-card.js.map"
$DeployInfo  = Join-Path $RemoteDir "deploy.txt"

Set-Location $ProjectRoot

Require-Command "npm"

if (-not $SkipBuild) {
    Step "Building yardian-card"
    npm run build
    if ($LASTEXITCODE -ne 0) {
        throw "npm run build failed."
    }
}

if (-not (Test-Path $Bundle)) {
    throw "Build artifact not found: $Bundle"
}

if (-not (Test-Path $BuildInfo)) {
    throw "Build metadata not found: $BuildInfo (expected to be generated by 'npm run build')."
}

# The build tag is generated exactly once, by vite.config.ts, and embedded
# directly into yardian-card.js. It is read here, never recomputed, so it
# always matches exactly what the browser will render.
$BuildTag = (Get-Content $BuildInfo -Raw | ConvertFrom-Json).buildTag
if ([string]::IsNullOrWhiteSpace($BuildTag)) {
    throw "build-info.json did not contain a 'buildTag' value."
}

if (-not (Test-Path $HaConfigDrive)) {
    throw "Home Assistant Samba drive '$HaConfigDrive' is not mounted/available."
}

Step "Preparing Home Assistant destination"
New-Item -ItemType Directory -Path $RemoteDir -Force | Out-Null

$LocalHash = (Get-FileHash -Algorithm SHA256 $Bundle).Hash
$ShortHash = $LocalHash.Substring(0, 12).ToLowerInvariant()
$Size      = (Get-Item $Bundle).Length

Step "Deploying yardian-card.js (build tag $BuildTag)"
Copy-Item -Path $Bundle -Destination $RemoteJs -Force

if (-not $NoSourceMap -and (Test-Path $SourceMap)) {
    Step "Deploying source map"
    Copy-Item -Path $SourceMap -Destination $RemoteMap -Force
}
elseif ($NoSourceMap -and (Test-Path $RemoteMap)) {
    Remove-Item $RemoteMap -Force
}

@"
build_tag=$BuildTag
sha256=$ShortHash
bytes=$Size
"@ | Set-Content -Path $DeployInfo -Encoding ascii

Step "Verifying deployed bundle"
if (-not (Test-Path $RemoteJs)) {
    throw "Deployed bundle is missing: $RemoteJs"
}

$RemoteHash = (Get-FileHash -Algorithm SHA256 $RemoteJs).Hash
$RemoteSize = (Get-Item $RemoteJs).Length

if ($RemoteHash -ne $LocalHash) {
    throw "Deploy verification failed: local and deployed SHA256 hashes differ."
}

if ($RemoteSize -ne $Size) {
    throw "Deploy verification failed: local bytes=$Size, deployed bytes=$RemoteSize"
}

Step "Updating Lovelace resource cache-bust query"

# lovelace_resources is HA's storage-mode registry of dashboard resource
# URLs (id/url/type records). We only ever touch the one record whose url
# is the yardian-card bundle; every other record round-trips unchanged.
$ResourceStore = Join-Path $HaConfigDrive ".storage\lovelace_resources"
if (-not (Test-Path $ResourceStore)) {
    throw "Lovelace resources storage not found: $ResourceStore"
}

$ResourceBackup = "$ResourceStore.bak.$((Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ'))"
Copy-Item -Path $ResourceStore -Destination $ResourceBackup -Force

$storageJson = (Get-Content -Path $ResourceStore -Raw) | ConvertFrom-Json

# Match the yardian-card bundle URL regardless of any existing query string.
$UrlPattern = '^/local/yardian-card/yardian-card\.js(\?.*)?$'
$matchingItems = @($storageJson.data.items | Where-Object { $_.url -match $UrlPattern })

if ($matchingItems.Count -eq 0) {
    throw "No lovelace resource entry matches /local/yardian-card/yardian-card.js in $ResourceStore."
}
if ($matchingItems.Count -gt 1) {
    throw "Found $($matchingItems.Count) lovelace resource entries matching /local/yardian-card/yardian-card.js; refusing to guess which one to update."
}

$NewResourceUrl = "/local/yardian-card/yardian-card.js?v=$ShortHash"
$matchingItems[0].url = $NewResourceUrl

# Write to a temp file in the same directory, then rename it over the
# original so a reader never observes a partially-written file. (True
# File.Replace-style atomic swap isn't available over the mapped SMB
# drive -- "the path is not of a legal form" -- so Move-Item -Force is
# the best available option here.) Written as UTF-8 *without* a BOM:
# HA's Python JSON loader would fail to parse a leading BOM byte.
$storageTemp = Join-Path (Split-Path -Parent $ResourceStore) "lovelace_resources.tmp"
$storageOut  = $storageJson | ConvertTo-Json -Depth 10
[System.IO.File]::WriteAllText($storageTemp, $storageOut, (New-Object System.Text.UTF8Encoding($false)))
Move-Item -Path $storageTemp -Destination $ResourceStore -Force

Write-Host ""
Write-Host "DEPLOY OK" -ForegroundColor Green
Write-Host "  Expected browser build tag: $BuildTag"
Write-Host "  Bundle hash: $ShortHash"
Write-Host "  Deployed: $RemoteJs"
Write-Host "  Lovelace resource updated to: $NewResourceUrl"
Write-Host "  Resource storage backup: $ResourceBackup"
Write-Host ""
Write-Host "Normal workflow:" -ForegroundColor Yellow
Write-Host "  .\deploy.ps1"
Write-Host ""
Write-Host "Compare the card's visible build tag in the browser against 'Expected browser build tag' above -- they must match exactly."
Write-Host "NOTE: Home Assistant keeps this resource list in memory; if the browser still doesn't pick up the new build tag after a normal reload, restart Home Assistant Core so it re-reads the updated resource URL." -ForegroundColor Yellow
